# Generated by Django 3.0.9 on 2020-09-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to='event_media/')),
                ('post_text', models.CharField(max_length=300)),
                ('post_date', models.DateTimeField()),
                ('post_title', models.CharField(max_length=10)),
            ],
        ),
    ]
